// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxmzfluhwuzaqbaibzwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4bXpmbHVod3V6YXFiYWliendtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTc4NTAsImV4cCI6MjA2NTU5Mzg1MH0.kr8hcdIdenzY8e5AORndvNZLBw1c4CdS5E9-k9pX7-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);